// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW47yaWwUQTwiBrUIuZ-XEMITSht-8cHM',
    appId: '1:889672779070:web:9041037bff08a96a99186f',
    messagingSenderId: '889672779070',
    projectId: 'authentication-2b2a6',
    authDomain: 'authentication-2b2a6.firebaseapp.com',
    storageBucket: 'authentication-2b2a6.appspot.com',
    measurementId: 'G-RWJ7DN89CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkj3_6LG8xPMAV9pS8X0n5XmCDOy3cqyE',
    appId: '1:889672779070:android:43353cf3ef7cdd1799186f',
    messagingSenderId: '889672779070',
    projectId: 'authentication-2b2a6',
    storageBucket: 'authentication-2b2a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNX9LHAYBU4AfXjezJ9WKLZfkbqWO4jQU',
    appId: '1:889672779070:ios:abb43fe0fcf588e999186f',
    messagingSenderId: '889672779070',
    projectId: 'authentication-2b2a6',
    storageBucket: 'authentication-2b2a6.appspot.com',
    iosClientId: '889672779070-c3lsqgscpdkg3enhli99bak9m6a5460q.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNX9LHAYBU4AfXjezJ9WKLZfkbqWO4jQU',
    appId: '1:889672779070:ios:abb43fe0fcf588e999186f',
    messagingSenderId: '889672779070',
    projectId: 'authentication-2b2a6',
    storageBucket: 'authentication-2b2a6.appspot.com',
    iosClientId: '889672779070-c3lsqgscpdkg3enhli99bak9m6a5460q.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationApp',
  );
}
